package me.caneva20.CNVRanks.Enums;

public enum FightingExpType {
    PLAYERS_PER_DAMAGE_DEALT,
    PLAYERS_PER_KILL,
    PASSIVE_MOBS_PER_DAMAGE_DEALT,
    PASSIVE_MOBS_PER_KILL,
    AGGRESSIVE_MOBS_PER_DAMAGE_DEALT,
    AGGRESSIVE_MOBS_PER_KILL
}
